### ISSUE TITLE
Issue 4 - Move the ball at a given speed

### ISSUE THREAD

**Issue by flaredragon** [IOSD/SUIG-JS#13]
Draw the ball and move it with speed 200 px per sec i.e every 10ms the canvas is cleared and new ball is made

**Comment by akshatbhargava123** [comment]
PR sent #19

**Comment by flaredragon** [comment]
@akshatbhargava123 please do the following changes in lesson2 file and update the PR

**Comment by akshatbhargava123** [comment]
@flaredragon I updated the PR in respective format, please accept it.

**Comment by flaredragon** [comment]
@akshatbhargava123 complete those functions in lesson2.html please.

**Comment by flaredragon** [comment]
don't make a new file
